# Responsible for analyzing repository files and generating documentation
# Currently mocked - returns hardcoded documentation for testing the full pipeline

from schemas import AgentRequest, AgentResponse, DocumentationSection

class AgentService:

    def analyze(self, request: AgentRequest) -> AgentResponse:
        sections = self._generate_mock_documentation(request)
        
        return AgentResponse(
            repo_name=request.repo_name,
            sections=sections,
            total_sections=len(sections)
        )

    def _generate_mock_documentation(self, request: AgentRequest) -> list[DocumentationSection]:
        return [
            DocumentationSection(
                title="Project Overview",
                content=f"This is the documentation for **{request.repo_name}**. "
                        f"This repository contains {request.total_files} files."
            ),
            DocumentationSection(
                title="File Structure",
                content=self._generate_file_structure(request)
            ),
            DocumentationSection(
                title="Getting Started",
                content="## Installation\n\n"
                        "1. Clone the repository\n"
                        "2. Install dependencies\n"
                        "3. Run the project\n\n"
                        "> This section will be AI generated in the final version."
            ),
            DocumentationSection(
                title="⚠️ Mock Notice",
                content="This documentation was generated by the **mocked** agent service. "
                        "Real AI-powered documentation coming soon!"
            )
        ]

    def _generate_file_structure(self, request: AgentRequest) -> str:
        structure = "```\n"
        for file in request.files[:20]:
            structure += f"{file.path}\n"
        if request.total_files > 20:
            structure += f"... and {request.total_files - 20} more files\n"
        structure += "```"
        return structure